package example.controllers;

import example.models.User;
import example.models.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import java.util.ArrayList;


@Controller //This class is a controller
public class MainController {
  @Autowired  // This means to get the bean called userRepository
              // Which is auto-generated by Spring, we will use it to handle the data

  private UserRepository userRepository;

  public String addNewUser( String name,  String email){
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    User n = new User();
    n.setName(name);
    n.setEmail(email);
    userRepository.save(n);
    return "true";

  }

  public  Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }
}
